server:
  port: 10001

logging:
  level:
    org.springframework.security: trace

spring:
  application:
    name: auth

  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
                - "client_secret_post"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:10002/login/oauth2/code/spring"
              post-logout-redirect-uris:
                - "http://127.0.0.1:10002/"
              scopes:
                - "openid"
                - "profile"
                - "user"
                - "email"

            require-authorization-consent: true

